#!/usr/bin/env python3
"""Dev key management for the simulator.

  keytool.py gen [--dir keys]              create an ECDSA P-256 keypair (skips if present)
  keytool.py header <pubkey_c_out> [--dir keys]   emit a C file defining safeflash_pubkey[64]

The private key stays in keys/ (gitignored). Only the derived public key gets baked into the bootloader.
"""
import argparse
import os
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


def priv_path(d):
    return os.path.join(d, "private.pem")


def load_private(d):
    with open(priv_path(d), "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def raw_pubkey(key) -> bytes:
    n = key.public_key().public_numbers()
    return n.x.to_bytes(32, "big") + n.y.to_bytes(32, "big")


def cmd_gen(a):
    os.makedirs(a.dir, exist_ok=True)
    if os.path.exists(priv_path(a.dir)):
        print(f"keep existing {priv_path(a.dir)}")
        return
    key = ec.generate_private_key(ec.SECP256R1())
    with open(priv_path(a.dir), "wb") as f:
        f.write(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                  serialization.NoEncryption()))
    print(f"wrote {priv_path(a.dir)}")


def cmd_header(a):
    raw = raw_pubkey(load_private(a.dir))
    body = ", ".join(f"0x{b:02x}" for b in raw)
    with open(a.out, "w", newline="\n") as f:
        f.write("/* Generated by tools/keytool.py. Do not edit. */\n#include <stdint.h>\n")
        f.write(f"const uint8_t safeflash_pubkey[64] = {{ {body} }};\n")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("gen")
    g.add_argument("--dir", default="keys")
    g.set_defaults(fn=cmd_gen)
    h = sub.add_parser("header")
    h.add_argument("out")
    h.add_argument("--dir", default="keys")
    h.set_defaults(fn=cmd_header)
    a = ap.parse_args()
    a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
